version: '3.6'

services:
  node:
    image: "node:16"
    container_name: nodejs
    build:
      context: ./server
      target: ${NODE_ENV}
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    user: "node"
    entrypoint: ["npm", "run", "server"]
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./:/home/node/app

  vite-front:
    container_name: vite-front
    build:
      context: ./front
      target: ${NODE_ENV}
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "${NODE_ENV}"]
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules

  postgres-14.5:
    container_name: postgres-14.5
    image: postgres:14.5
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres-14.5

  pgadmin4:
    links:
    - postgres-14.5:postgres-14.5
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres-14.5

networks:
  postgres-14.5:
    driver: bridge
