version: '3.6'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
      - '3002:3002'
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - db

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    user: "node"
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    volumes:
      - ./front:/usr/src/app

  db:
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - .env

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    depends_on:
      - db